apiVersion: v1
kind: Service
metadata:
  name: selenium-hub-np
  labels:
    app: selenium-hub-nodePort
spec:
  ports:
  - port: 4444
    targetPort: 4444
    name: port0
  selector:
    app: selenium-hub
  type: NodePort
  sessionAffinity: None
